image: gitlab/dind
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - test
  - docker

maven-build:
  image: maven:latest
  stage: build
  script:
    - echo "Compiling the code..."
    - "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar

maven-test:
  image: maven:latest
  stage: test
  script:
    - echo "Running tests..." 
    - mvn test
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker
  script:
    - echo "Building and publishing Docker Image..."
    - mvn compile com.google.cloud.tools:jib-maven-plugin:build \
      -Djib.to.auth.username=${CI_REGISTRY_USER} \
      -Djib.to.auth.password=${CI_REGISTRY_PASSWORD} \
      -Djib.to.image=${CI_REGISTRY_IMAGE}:latest
