version: "3.3"

##############################################################################
#                             ePAS Service                                   #
# Configurazione per l'avvio di ePAS Service collegandosi ad un database di  #
# ePAS esistente                                                             #
##############################################################################

services:
  epas-service:
    image: ghcr.io/consiglionazionaledellericerche/epas-service:latest
    container_name: epas-service
    ports:
      - 8080:8080
    environment:
      - spring_datasource_url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - spring_datasource_username=${DB_USER}
      - spring_datasource_password=${DB_PASS}
